
name: Generate Snake and Pacman

on:
  schedule:
    - cron: "0 0 * * *"  # todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake and Pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: yMistikTK
          outputs: |
            dist/snake.svg
            dist/pacman-contribution-graph.svg

      - name: Commit and push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
